/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Tom�
 * Created: 12.4.2016
 */

CREATE TABLE band (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(40),
	region INT,
	pricePerHour Double,
	rate Double
);

CREATE TABLE customer (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50),
	phoneNumber VARCHAR(20),
	address VARCHAR(50)
);

CREATE TABLE lease (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	idBand BIGINT REFERENCES band(id),
	idCustomer BIGINT REFERENCES customer(id),
	date VARCHAR(30),
	region INT,
	duration INT
);

CREATE TABLE band_styles (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	idBand BIGINT REFERENCES band(id),
	style INT
);