/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.bandsproject;

/**
 *
 * @author Tomáš
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        contentPanel.removeAll();
        contentPanel.add(firstContent);
        contentPanel.repaint();
        contentPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bandsButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        ordersButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        listBand = new javax.swing.JPanel();
        bandListLabel = new javax.swing.JLabel();
        bandTableScroll = new javax.swing.JScrollPane();
        bandTable = new javax.swing.JTable();
        addBandButton = new javax.swing.JButton();
        firstContent = new javax.swing.JPanel();
        listCustomer = new javax.swing.JPanel();
        customerListLabel = new javax.swing.JLabel();
        customerTableScroll = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        addCustomerButton = new javax.swing.JButton();
        listOrders = new javax.swing.JPanel();
        orderListLabel = new javax.swing.JLabel();
        orderTableScroll = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addOrderButton = new javax.swing.JButton();
        createOrder = new javax.swing.JPanel();
        createOrderLabel = new javax.swing.JLabel();
        orderBandSelect = new javax.swing.JComboBox<>();
        orderBandLabel = new javax.swing.JLabel();
        orderCustomerLabel = new javax.swing.JLabel();
        orderCustomerSelect = new javax.swing.JComboBox<>();
        orderDurationSelect = new javax.swing.JSpinner();
        orderDurationLabel = new javax.swing.JLabel();
        orderRegionSelect = new javax.swing.JComboBox<>();
        orderRegionLabel = new javax.swing.JLabel();
        orderDateLabel = new javax.swing.JLabel();
        orderDateSelect = new javax.swing.JSpinner();
        createOrderButton = new javax.swing.JButton();
        createCustomer = new javax.swing.JPanel();
        createCustomerLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        customerAddressText = new javax.swing.JTextField();
        customerAddressLabel = new javax.swing.JLabel();
        customerPhoneText = new javax.swing.JTextField();
        customerPhoneLabel = new javax.swing.JLabel();
        customerNameText = new javax.swing.JTextField();
        createCustomerButton = new javax.swing.JButton();
        createBand = new javax.swing.JPanel();
        createBandLabel = new javax.swing.JLabel();
        bandNameText = new javax.swing.JTextField();
        bandNameLabel = new javax.swing.JLabel();
        bandRegionSelect = new javax.swing.JComboBox<>();
        bandRegionLabel = new javax.swing.JLabel();
        bandStylesSelect = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bandStylesLabel = new javax.swing.JLabel();
        bandPriceText = new javax.swing.JTextField();
        bandPriceLabel = new javax.swing.JLabel();
        createBandButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Band Manager");

        bandsButton.setText("Bands");
        bandsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandsButtonActionPerformed(evt);
            }
        });

        customersButton.setText("Customers");
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });

        ordersButton.setText("Orders");
        ordersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(bandsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bandsButton)
                    .addComponent(customersButton)
                    .addComponent(ordersButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());

        bandListLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bandListLabel.setText("Bands");

        bandTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bandTableScroll.setViewportView(bandTable);

        addBandButton.setText("Add");
        addBandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listBandLayout = new javax.swing.GroupLayout(listBand);
        listBand.setLayout(listBandLayout);
        listBandLayout.setHorizontalGroup(
            listBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listBandLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(listBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBandButton)
                    .addComponent(bandListLabel)
                    .addComponent(bandTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        listBandLayout.setVerticalGroup(
            listBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listBandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bandListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bandTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBandButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contentPanel.add(listBand, "card2");

        javax.swing.GroupLayout firstContentLayout = new javax.swing.GroupLayout(firstContent);
        firstContent.setLayout(firstContentLayout);
        firstContentLayout.setHorizontalGroup(
            firstContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
        );
        firstContentLayout.setVerticalGroup(
            firstContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        contentPanel.add(firstContent, "card5");

        customerListLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customerListLabel.setText("Customers");

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerTableScroll.setViewportView(customerTable);

        addCustomerButton.setText("Add");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listCustomerLayout = new javax.swing.GroupLayout(listCustomer);
        listCustomer.setLayout(listCustomerLayout);
        listCustomerLayout.setHorizontalGroup(
            listCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listCustomerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(listCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerButton)
                    .addComponent(customerListLabel)
                    .addComponent(customerTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        listCustomerLayout.setVerticalGroup(
            listCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addCustomerButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contentPanel.add(listCustomer, "card2");

        orderListLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderListLabel.setText("Orders");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderTableScroll.setViewportView(orderTable);

        addOrderButton.setText("Add");
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listOrdersLayout = new javax.swing.GroupLayout(listOrders);
        listOrders.setLayout(listOrdersLayout);
        listOrdersLayout.setHorizontalGroup(
            listOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listOrdersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(listOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addOrderButton)
                    .addComponent(orderListLabel)
                    .addComponent(orderTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        listOrdersLayout.setVerticalGroup(
            listOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addOrderButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contentPanel.add(listOrders, "card2");

        createOrderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createOrderLabel.setText("Create Order");

        orderBandSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        orderBandLabel.setText("Band:");

        orderCustomerLabel.setText("Customer:");

        orderCustomerSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        orderDurationSelect.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        orderDurationLabel.setText("Duration:");

        orderRegionSelect.setModel(new javax.swing.DefaultComboBoxModel<>(Region.values()));
        orderRegionSelect.setSelectedIndex(0);

        orderRegionLabel.setText("Region:");

        orderDateLabel.setText("Date:");

        orderDateSelect.setModel(new javax.swing.SpinnerDateModel());

        createOrderButton.setText("Create");

        javax.swing.GroupLayout createOrderLayout = new javax.swing.GroupLayout(createOrder);
        createOrder.setLayout(createOrderLayout);
        createOrderLayout.setHorizontalGroup(
            createOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(createOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(orderDateLabel)
                        .addComponent(orderRegionLabel)
                        .addComponent(orderDurationLabel)
                        .addComponent(orderCustomerLabel)
                        .addComponent(orderBandLabel)
                        .addComponent(createOrderLabel)
                        .addComponent(orderDurationSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orderBandSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderCustomerSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderRegionSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(orderDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(732, Short.MAX_VALUE))
        );
        createOrderLayout.setVerticalGroup(
            createOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createOrderLabel)
                .addGap(18, 18, 18)
                .addComponent(orderBandLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderBandSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderCustomerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCustomerSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderRegionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderRegionSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderDateLabel)
                .addGap(5, 5, 5)
                .addComponent(orderDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderDurationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderDurationSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(createOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        contentPanel.add(createOrder, "card8");

        createCustomerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createCustomerLabel.setText("Create customer");

        customerNameLabel.setText("Name:");

        customerAddressText.setToolTipText("Fill the customer address");

        customerAddressLabel.setText("Address");

        customerPhoneText.setToolTipText("Fill the customer phone");

        customerPhoneLabel.setText("Phone:");

        customerNameText.setToolTipText("Fill the customer name");

        createCustomerButton.setText("Create");

        javax.swing.GroupLayout createCustomerLayout = new javax.swing.GroupLayout(createCustomer);
        createCustomer.setLayout(createCustomerLayout);
        createCustomerLayout.setHorizontalGroup(
            createCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(createCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPhoneLabel)
                    .addComponent(customerPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerAddressLabel)
                    .addComponent(customerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameLabel)
                    .addComponent(createCustomerLabel))
                .addContainerGap(654, Short.MAX_VALUE))
        );
        createCustomerLayout.setVerticalGroup(
            createCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createCustomerLabel)
                .addGap(18, 18, 18)
                .addComponent(customerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerPhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(createCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        contentPanel.add(createCustomer, "card8");

        createBandLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createBandLabel.setText("Create band");

        bandNameText.setToolTipText("Fill the band name");

        bandNameLabel.setText("Name:");

        bandRegionSelect.setModel(new javax.swing.DefaultComboBoxModel<>(Region.values()));
        bandRegionSelect.setSelectedIndex(0);

        bandRegionLabel.setText("Region: ");

        jList1.setModel(new javax.swing.DefaultComboBoxModel<>(Style.values()));
        bandStylesSelect.setViewportView(jList1);

        bandStylesLabel.setText("Styles:");

        bandPriceText.setToolTipText("Fill the price of band");

        bandPriceLabel.setText("Price per hour:");

        createBandButton.setText("Create");

        javax.swing.GroupLayout createBandLayout = new javax.swing.GroupLayout(createBand);
        createBand.setLayout(createBandLayout);
        createBandLayout.setHorizontalGroup(
            createBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createBandLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(createBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createBandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bandPriceLabel)
                    .addComponent(bandStylesLabel)
                    .addComponent(bandRegionLabel)
                    .addComponent(createBandLabel)
                    .addComponent(bandNameLabel)
                    .addComponent(bandStylesSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bandRegionSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bandNameText)
                    .addComponent(bandPriceText))
                .addContainerGap(636, Short.MAX_VALUE))
        );
        createBandLayout.setVerticalGroup(
            createBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createBandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createBandLabel)
                .addGap(18, 18, 18)
                .addComponent(bandNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bandRegionLabel)
                .addGap(5, 5, 5)
                .addComponent(bandRegionSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(bandStylesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandStylesSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bandPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(createBandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        contentPanel.add(createBand, "card7");

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bandsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandsButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(listBand);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_bandsButtonActionPerformed

    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(createOrder);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_addOrderButtonActionPerformed

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(listCustomer);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_customersButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(listOrders);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_ordersButtonActionPerformed

    private void addBandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBandButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(createBand);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_addBandButtonActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(createCustomer);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBandButton;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addOrderButton;
    private javax.swing.JLabel bandListLabel;
    private javax.swing.JLabel bandNameLabel;
    private javax.swing.JTextField bandNameText;
    private javax.swing.JLabel bandPriceLabel;
    private javax.swing.JTextField bandPriceText;
    private javax.swing.JLabel bandRegionLabel;
    private javax.swing.JComboBox<Region> bandRegionSelect;
    private javax.swing.JLabel bandStylesLabel;
    private javax.swing.JScrollPane bandStylesSelect;
    private javax.swing.JTable bandTable;
    private javax.swing.JScrollPane bandTableScroll;
    private javax.swing.JButton bandsButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel createBand;
    private javax.swing.JButton createBandButton;
    private javax.swing.JLabel createBandLabel;
    private javax.swing.JPanel createCustomer;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JLabel createCustomerLabel;
    private javax.swing.JPanel createOrder;
    private javax.swing.JButton createOrderButton;
    private javax.swing.JLabel createOrderLabel;
    private javax.swing.JLabel customerAddressLabel;
    private javax.swing.JTextField customerAddressText;
    private javax.swing.JLabel customerListLabel;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JLabel customerPhoneLabel;
    private javax.swing.JTextField customerPhoneText;
    private javax.swing.JTable customerTable;
    private javax.swing.JScrollPane customerTableScroll;
    private javax.swing.JButton customersButton;
    private javax.swing.JPanel firstContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Style> jList1;
    private javax.swing.JPanel listBand;
    private javax.swing.JPanel listCustomer;
    private javax.swing.JPanel listOrders;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel orderBandLabel;
    private javax.swing.JComboBox<String> orderBandSelect;
    private javax.swing.JLabel orderCustomerLabel;
    private javax.swing.JComboBox<String> orderCustomerSelect;
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JSpinner orderDateSelect;
    private javax.swing.JLabel orderDurationLabel;
    private javax.swing.JSpinner orderDurationSelect;
    private javax.swing.JLabel orderListLabel;
    private javax.swing.JLabel orderRegionLabel;
    private javax.swing.JComboBox<Region> orderRegionSelect;
    private javax.swing.JTable orderTable;
    private javax.swing.JScrollPane orderTableScroll;
    private javax.swing.JButton ordersButton;
    // End of variables declaration//GEN-END:variables
}
